export const packageRuffData = [
    {
        _id: 1,
        name: "String",
        price: 55,
        startDate: "24/09/2024",
        endDate: "28/09/2024",
        totalPeople: "5 person",
        description: "Description",
        country: "Canada",
        location: "Singapore",
    },
    {
        _id: 2,
        name: "String",
        price: 55,
        startDate: "24/09/2024",
        endDate: "28/09/2024",
        totalPeople: "5 person",
        description: "Description",
        country: "Canada",
        location: "Singapore",
    },
    {
        _id: 3,
        name: "String",
        price: 55,
        startDate: "24/09/2024",
        endDate: "28/09/2024",
        totalPeople: "5 person",
        description: "Description",
        country: "Canada",
        location: "Singapore",
    },
    {
        _id: 4,
        name: "String",
        price: 55,
        startDate: "24/09/2024",
        endDate: "28/09/2024",
        totalPeople: "5 person",
        description: "Description",
        country: "Canada",
        location: "Singapore",
    },
    {
        _id: 5,
        name: "String",
        price: 55,
        startDate: "24/09/2024",
        endDate: "28/09/2024",
        totalPeople: "5 person",
        description: "Description",
        country: "Canada",
        location: "Singapore",
    },
    {
        _id: 6,
        name: "String",
        price: 55,
        startDate: "24/09/2024",
        endDate: "28/09/2024",
        totalPeople: "5 person",
        description: "Description",
        country: "Canada",
        location: "Singapore",
    },
];
